import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faUser,
  faLock,
  faSignOutAlt,
  faCog,
  faPlus,
  faBars,
  faArrowLeft,
  faArrowRight,
  faCaretDown,
  faCaretUp,
  faCommentDollar,
  faComment,
  faHeart,
  faShare,
  faFilter,
  faThumbsUp,
  faFlag,
  faAlignLeft,
  faGlobe,
  faFileAlt,
  faTrashAlt,
  faParagraph,
  faDollarSign,
  faGraduationCap,
  faCode,
  faLink,
  faKeyboard,
} from '@fortawesome/free-solid-svg-icons';

import {
  faThumbsUp as regularThumbsUp,
  faClipboard,
  faImage,
  faEnvelope,
} from '@fortawesome/free-regular-svg-icons';

import {
  faYoutube,
  faInstagram,
  faTwitter,
  faGithub,
} from '@fortawesome/free-brands-svg-icons';

// import {
//   faHeart,
// } from '@fortawesome/free-regular-svg-icons';

library.add(
  faUser,
  faLock,
  faSignOutAlt,
  faCog,
  faPlus,
  faBars,
  faArrowLeft,
  faArrowRight,
  faCaretDown,
  faCaretUp,
  faComment,
  faHeart,
  faShare,
  faFilter,
  faThumbsUp,
  regularThumbsUp,
  faFlag,
  faCommentDollar,
  faClipboard,
  faYoutube,
  faImage,
  faAlignLeft,
  faGlobe,
  faFileAlt,
  faTrashAlt,
  faParagraph,
  faInstagram,
  faTwitter,
  faDollarSign,
  faGraduationCap,
  faGithub,
  faCode,
  faLink,
  faKeyboard,
  faEnvelope,
);
